### PR TITLE
Fix #86, #87, #90

### LINKED ISSUE #86: Finish bootstrap UI port
There is a partial port of the UI to Bootstrap.  This looks pretty, but needs some finishing.

Need to port these views:

- index
- group
- monitor

### PR DESCRIPTION
**Pull request by micolous**
Fix issues #86, #87, #90.  Bootstrap is still missing on the main page but at least gives a better view on the video page with less chrome.

### CODE REVIEW

**Comment by aps-sids** [comment]
LGTM! @micolous Have you tested the JSON feed import?

**Comment by micolous** [comment]
@aps-sids The JSON feed works for LCA's current feed.  I've added a few extra checks in order to deal with import issues are handled.  There were some formats around 2012.

**Comment by aps-sids** [comment]
Okay. Do you want to port remaining pages to bootstrap as well or merge this right away?

**Comment by micolous** [comment]
I want to merge this stuff now.

The "index" page is a bit harder, and a lower priority so I'll look at it later.

The "monitor" page is easier, but it's still a lower priority than other issues that @mithro wants to look at

**Pull request merged**
